package np.qa.diploma.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserFull {
    private String id;
    private String title;
    private String firstName;
    private String lastName;
    private String registerDate;

    /*
    gender: string("male", "female", "other", "")
    email: string(email)
    dateOfBirth: string(ISO Date - value: 1/1/1900 - now)
    registerDate: string(autogenerated)
    phone: string(phone number - any format)
    picture: string(url)
    location: object(Location)*/
}
